export const OPEN_INSTAGRAM_LINK = 'OPEN_INSTAGRAM_LINK'
export const SET_SERVICE_SEARCH = 'SET_SERVICE_SEARCH'
export const SET_POSTAL_CODE_SEARCH = 'SET_POSTAL_CODE_SEARCH'
export const SET_DATE_SEARCH = 'SET_DATE_SEARCH'
