version: "3.2"
services:
  db:
    image: postgres
    restart: always
    environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: bash -c "python manage.py wait_for_db && python manage.py migrate && gunicorn orgasmi_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: bash -c "npm install && npm start"

volumes: 
     pgdata: