# Generated by Django 2.2.4 on 2019-09-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgasmi_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orgasmi_backend.Review'),
        ),
    ]
