# Generated by Django 2.2.5 on 2019-09-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgasmi_backend', '0003_auto_20190904_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMacroCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Macro Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Tag description')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tip name')),
                ('description', models.TextField(verbose_name='Tag description')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='duration_in_weeks',
            field=models.IntegerField(default=2, verbose_name='Duration of service in weeks'),
        ),
        migrations.AddField(
            model_name='service',
            name='execution_time_in_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(default=0, verbose_name='Short Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Name of the service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orgasmi_backend.ServiceCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='macro_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='orgasmi_backend.ServiceMacroCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='service_tags', to='orgasmi_backend.Tag'),
        ),
        migrations.AddField(
            model_name='service',
            name='tips',
            field=models.ManyToManyField(blank=True, related_name='service_tips', to='orgasmi_backend.Tip'),
        ),
    ]
