# Generated by Django 2.2.5 on 2019-09-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgasmi_backend', '0004_auto_20190924_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orgasmi_backend.ServiceCategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='macro_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='orgasmi_backend.ServiceMacroCategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
    ]
